server:
  port: 8043

spring:
  application:
    name: LMS_System_Api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  security:
     oauth2:
       resource-server:
         jwt:
           issuer-uri: http://localhost:8081/realms/auth/realms/lms-realm
           jwk-set-uri: http://localhost:8081/auth/realms/lms-realm/protocol/openid-connect/certs

  liquibase:
    change-log: classpath:db/changelog/changelog.xml

logging:
  level:
    com.example.lms_system_api: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

