server:
  port: 8043

spring:
  application:
    name: LMS_System_Api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/lms_realm
  liquibase:
    change-log: classpath:db/changelog/changelog.xml

logging:
  level:
    com.example.lms_system_api: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

keycloak:
  token-uri: http://localhost:8081/auth/realms/lms_realm/protocol/openid-connect/token
  client-id: lms-client
  client-secret: ni2dFtqNotqKaNAfi7kYqYITONcyMrRd
  admin:
    server-url: http://localhost:8081/auth
    realm: lms_realm
    client-id: lms-client
    client-secret: ni2dFtqNotqKaNAfi7kYqYITONcyMrRd
    username: admin
    password: admin


